package club.banyuan.blog.model;

import java.io.Serializable;
import java.util.Date;

public class TagQuestionRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_question_relation.id
     *
     * @mbg.generated Wed Jun 17 20:49:22 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_question_relation.question_id
     *
     * @mbg.generated Wed Jun 17 20:49:22 CST 2020
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_question_relation.tag_id
     *
     * @mbg.generated Wed Jun 17 20:49:22 CST 2020
     */
    private Integer tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag_question_relation.created_at
     *
     * @mbg.generated Wed Jun 17 20:49:22 CST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tag_question_relation
     *
     * @mbg.generated Wed Jun 17 20:49:22 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_question_relation.id
     *
     * @return the value of tag_question_relation.id
     *
     * @mbg.generated Wed Jun 17 20:49:22 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_question_relation.id
     *
     * @param id the value for tag_question_relation.id
     *
     * @mbg.generated Wed Jun 17 20:49:22 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_question_relation.question_id
     *
     * @return the value of tag_question_relation.question_id
     *
     * @mbg.generated Wed Jun 17 20:49:22 CST 2020
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_question_relation.question_id
     *
     * @param questionId the value for tag_question_relation.question_id
     *
     * @mbg.generated Wed Jun 17 20:49:22 CST 2020
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_question_relation.tag_id
     *
     * @return the value of tag_question_relation.tag_id
     *
     * @mbg.generated Wed Jun 17 20:49:22 CST 2020
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_question_relation.tag_id
     *
     * @param tagId the value for tag_question_relation.tag_id
     *
     * @mbg.generated Wed Jun 17 20:49:22 CST 2020
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag_question_relation.created_at
     *
     * @return the value of tag_question_relation.created_at
     *
     * @mbg.generated Wed Jun 17 20:49:22 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag_question_relation.created_at
     *
     * @param createdAt the value for tag_question_relation.created_at
     *
     * @mbg.generated Wed Jun 17 20:49:22 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag_question_relation
     *
     * @mbg.generated Wed Jun 17 20:49:22 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", questionId=").append(questionId);
        sb.append(", tagId=").append(tagId);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}