package club.banyuan.studyroom.model;

import java.io.Serializable;
import java.util.Date;

public class Books implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.id
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.user_id
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.seat_id
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    private Integer seatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.created_at
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.hours
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    private String hours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column books.book_status
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    private Boolean bookStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table books
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.id
     *
     * @return the value of books.id
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.id
     *
     * @param id the value for books.id
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.user_id
     *
     * @return the value of books.user_id
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.user_id
     *
     * @param userId the value for books.user_id
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.seat_id
     *
     * @return the value of books.seat_id
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    public Integer getSeatId() {
        return seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.seat_id
     *
     * @param seatId the value for books.seat_id
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    public void setSeatId(Integer seatId) {
        this.seatId = seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.created_at
     *
     * @return the value of books.created_at
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.created_at
     *
     * @param createdAt the value for books.created_at
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.hours
     *
     * @return the value of books.hours
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    public String getHours() {
        return hours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.hours
     *
     * @param hours the value for books.hours
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    public void setHours(String hours) {
        this.hours = hours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column books.book_status
     *
     * @return the value of books.book_status
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    public Boolean getBookStatus() {
        return bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column books.book_status
     *
     * @param bookStatus the value for books.book_status
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    public void setBookStatus(Boolean bookStatus) {
        this.bookStatus = bookStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table books
     *
     * @mbg.generated Tue Jun 23 10:35:02 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", seatId=").append(seatId);
        sb.append(", createdAt=").append(createdAt);
        sb.append(", hours=").append(hours);
        sb.append(", bookStatus=").append(bookStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}